/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OPT_UI;

/**
 *
 * @author kumars2
 */
public class Save_details extends javax.swing.JPanel {

    OPT_hostframe parent_;
    /**
     * Creates new form Save_details
     */
    public Save_details() {
        initComponents();
    }
    
    public void initialise(OPT_hostframe parent_ref){
        parent_ = parent_ref;
    }    
    
    public String get_savepath(){
        return save_path.getText();
    }
    
    public String get_savechoice(){
        return Save_choice.getItemAt(Save_choice.getSelectedIndex()).toString();
    }    
    
    public String get_samplename(){
        return sample_name.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Save_choice = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        save_path = new javax.swing.JTextField();
        sample_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        testbutton = new javax.swing.JButton();

        Save_choice.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Auto-path", "Selected path" }));

        jLabel1.setText("Save settings");

        save_path.setText("C:\\TMP\\MMtest");

        sample_name.setText("SAMPLE_0");
        sample_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sample_nameActionPerformed(evt);
            }
        });

        jLabel2.setText("Sample ID");

        testbutton.setText("TEST");
        testbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Save_choice, 0, 124, Short.MAX_VALUE)
                    .addComponent(sample_name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(save_path, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(testbutton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Save_choice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(save_path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sample_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(testbutton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sample_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sample_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sample_nameActionPerformed

    private void testbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testbuttonActionPerformed
        parent_.run_test();
    }//GEN-LAST:event_testbuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Save_choice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField sample_name;
    private javax.swing.JTextField save_path;
    private javax.swing.JButton testbutton;
    // End of variables declaration//GEN-END:variables
}
